-- Table pour la gestion des versions de l'application Pseudo Code
-- Supporte Android (APK) et Windows (EXE/MSIX)

CREATE TABLE IF NOT EXISTS public.pseudo_code_app_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    version_code INTEGER NOT NULL,
    version_name TEXT NOT NULL,
    platform TEXT NOT NULL CHECK (platform IN ('android', 'windows', 'linux')),
    file_url TEXT NOT NULL, -- Nom du fichier sur Backblaze B2 (ex: pseudo_code_v1.0.0.apk)
    is_forced BOOLEAN DEFAULT FALSE,
    release_notes TEXT,
    
    -- Unicité par plateforme et version code
    UNIQUE(platform, version_code)
);

-- Activation de RLS (Row Level Security)
ALTER TABLE public.pseudo_code_app_versions ENABLE ROW LEVEL SECURITY;

-- Politique de lecture publique
CREATE POLICY "Lecture publique des versions" 
ON public.pseudo_code_app_versions 
FOR SELECT 
TO anon 
USING (true);

-- Politique d'écriture réservée au service_role (déploiement)
CREATE POLICY "Ecriture reservée au service_role" 
ON public.pseudo_code_app_versions 
FOR ALL 
TO service_role 
USING (true) 
WITH CHECK (true);
